---
# tasks file for ansible-terminal

# iTerm.app
- name: '[main] Ensure iTerm2 is installed using Homebrew Cask'
  homebrew_cask:
    name: iterm2
    state: present
    #install_options: "appdir= ~/Applications"
  register: macos_terminal_iterm2_result
  until: macos_terminal_iterm2_result is succeeded
  when: macos_terminal_iterm2
  tags: macos_terminal

- name: '[main] Make sure iTerm2 is not running'
  shell: pgrep iTerm2 && killall iTerm2 && sleep 10 || echo 'iTerm2_NOT_STARTED'
  register: macos_terminal_pkill
  changed_when: "'iTerm2_NOT_STARTED' not in macos_terminal_pkill.stdout"
  when: macos_terminal_iterm2
  tags: macos_terminal

- name: '[main] Copy iTerm2 preferences'
  copy:
    src: com.googlecode.iterm2.plist
    dest: ~/Library/Preferences/
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0600
  when: macos_terminal_iterm2
  notify: Read new iTerm profile after copying
  tags: macos_terminal

# Mac OS Terminal.app
- name: '[main] Make sure Terminal app is not running'
  shell: pgrep Terminal && killall Terminal && sleep 10 || echo 'Terminal_app_NOT_STARTED'
  register: macos_terminal_app_pkill
  changed_when: "'Terminal_app_NOT_STARTED' not in macos_terminal_app_pkill.stdout"
  tags: macos_terminal

- name: '[main] Copy Terminal app preferences'
  copy:
    src: com.apple.Terminal.plist
    dest: ~/Library/Preferences/
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0600
  tags: macos_terminal

#  - defaults write com.apple.Terminal 'Default Window Settings' -string 'Solarized_Dark_custom'
- name: '[main] Ensure {{ macos_terminal_colorscheme }} profile is set as default'
  osx_defaults:
    domain: com.apple.Terminal
    state: present
    key: "{{ item }}"
    type: string
    value: "{{ macos_terminal_colorscheme }}"
  with_items:
  - 'Default Window Settings'
  - 'Startup Window Settings'
  tags: macos_terminal

- meta: flush_handlers
  tags: macos_terminal
...
